[package]
name = "oubli"
description = "Library for generating documentation websites with Maudit."
version = "0.1.13"
license = "MIT"
edition = "2024"

[dependencies]
maudit = { path = "../maudit", version = "0.8.0" }
maud = { workspace = true }
serde = { workspace = true }
