[package]
name = "maudit-website"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
maudit = { workspace = true }
maud = { workspace = true }
serde = { workspace = true }
chrono = { version = "0.4.43", features = ["serde"] }
